src/main/java/model/Point.java
package model;

/**
 * Class representing a single point in space and time.
 */
public class Point implements Comparable<Point> {
    private int timestamp;
    private double xPos, yPos, zPos;

    /**
     * constructor.
     *
     * @param timestamp time at which the point was measured.
     * @param x         x-coordinate of the point.
     * @param y         y-coordinate of the point.
     * @param z         x-coordinate of the point.
     */
    public Point(int timestamp, double x, double y, double z) {
        this.timestamp = timestamp;
        this.xPos = x;
        this.yPos = y;
        this.zPos = z;
    }

    /**
     * Compares this to another point.
     * The point with the largest timestamp is the biggest one.
     *
     * @param o point to compare to/
     * @return -1 if this.timestamp < o.timestamp,
     * 0 if this.timestamp == o.timestamp,
     * 1 if this.timestamp > o.timestamp</>
     */
    @Override
    public int compareTo(Point o) {
        return Integer.compare(this.timestamp, o.timestamp);
    }

    /**
     * @return String representation of the Point.
     */
    @Override
    public String toString() {
        return "Point{" +
                "timestamp=" + timestamp +
                ", xPos=" + xPos +
                ", yPos=" + yPos +
                ", zPos=" + zPos +
                '}';
    }

    /**
     * @return the timestamp of the point.
     */
    public int getTimestamp() {
        return timestamp;
    }

    /**
     * @return The x-coordinate of the point.
     */
    public double getXpos() {
        return xPos;
    }

    /**
     * @return The y-coordinate of the point.
     */
    public double getYpos() {
        return yPos;
    }

    /**
     * @return the z-coordinate of the point.
     */
    public double getZpos() {
        return zPos;
    }
}

src/main/java/model/Trajectory.java
package model;

import com.sun.istack.internal.NotNull;

import java.util.ArrayList;
import java.util.List;

/**
 * Class representing a path through space.
 */
public class Trajectory {
    private TrajectorySpecifier specifier;
    private ArrayList<Double> xPositions = new ArrayList<>(),
            yPositions = new ArrayList<>(),
            zPositions = new ArrayList<>();

    /**
     * constructor
     * @param specifier TrajectorySpecifier describing the experimental origin of the trajectory.
     */
    public Trajectory(@NotNull TrajectorySpecifier specifier){
        if(specifier == null){
            throw new IllegalArgumentException("Received null for TrajectorySpecifier");
        }
        this.specifier = specifier;
    }

    /**
     * Adds a Point to the end of the trajectory.
     */
    public void addPoint(Point point){
        addPoint(point.getXpos(), point.getYpos(), point.getZpos());
    }

    /**
     * adds a point to the end of the trajectory.
     * @param xPos x position of the point to add.
     * @param yPos y position of the point to add.
     * @param zPos z position of the point to add.
     */
    public void addPoint(double xPos, double yPos, double zPos){
        this.xPositions.add(xPos);
        this.yPositions.add(yPos);
        this.zPositions.add(zPos);
    }

    /**
     * @return list containing Points, in the order they were inserted.
     * the timestamp of each point will be the index of the point within the trajectory.
     */
    public List<Point> getPoints(){
        ArrayList<Point> points = new ArrayList<>();
        for(int i=0; i < this.xPositions.size(); i++){
            points.add(new Point(i, xPositions.get(i), yPositions.get(i), zPositions.get(i)));
        }
        return points;
    }

    /**
     * @return TrajectorySpecifier describing the experimental origin of the trajectory.
     */
    public TrajectorySpecifier getSpecifier() {
        return specifier;
    }

    @Override
    public String toString() {
        return "Trajectory{" +
                "specifier=" + specifier +
                ", number of points:" + zPositions.size() +
                '}';
    }
}

src/main/webapp/xml/error.jsp
<%--
  Created by IntelliJ IDEA.
  User: ddubber
  Date: 7-12-17
  Time: 15:33
  To change this template use File | Settings | File Templates.
--%>
<%@page contentType="application/xml" pageEncoding="UTF-8" language="java"%>

<error>${requestScope.error.message}</error>

src/main/webapp/xml/succesfulDelete.jsp
<%--
  Created by IntelliJ IDEA.
  User: ddubber
  Date: 10-1-18
  Time: 10:23
  To change this template use File | Settings | File Templates.
--%>
<%@page contentType="application/xml" pageEncoding="UTF-8" language="java"%>

<success>Successfully deleted ${requestScope.deletes}.</success>

src/main/webapp/xml/successfulUpload.jsp
<%--
  Created by IntelliJ IDEA.
  User: Johan
  Date: 5-1-2018
  Time: 19:01
  To change this template use File | Settings | File Templates.
--%>
<%@page contentType="application/xml" pageEncoding="UTF-8" language="java"%>

<success>Successfully uploaded ${requestScope.numberOfFiles} files.</success>

src/main/webapp/xml/trajectory.jsp
<%--
  Created by IntelliJ IDEA.
  User: ddubber
  Date: 22-12-17
  Time: 9:00
  To change this template use File | Settings | File Templates.
--%>
<%@page contentType="application/xml" pageEncoding="UTF-8" language="java"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!-- template for ajax response -->
<points>
    <c:forEach var="point" items="${requestScope.points}">
        <point>
            <x>${point.xpos}</x>
            <y>${point.ypos}</y>
            <z>${point.zpos}</z>
        </point>
    </c:forEach>
</points>